name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - main  # You can change this to your desired branch (e.g., master, develop)

jobs:
  build:
    runs-on: ubuntu-latest  # The OS to run the job on

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3  # This action checks out your repository's code

      # Step 2: Set up Docker Buildx (for advanced features and multi-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # This sets up Docker Buildx

      # Step 3: Cache Docker layers to speed up builds
      - name: Cache Docker layers
        uses: actions/cache@v2  # This caches Docker layers for faster builds
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      # Step 4: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}  # GitHub username
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub token (this is automatically provided)

      # Step 5: Build and Push Docker image to GHCR
      - name: Build and push Docker image
        run: |
          docker buildx build --push --tag ghcr.io/${{ github.repository_owner }}/yourimagename:latest .
